package peoplebrowser

import (
	"fmt"

	"go.kenn.io/msgvault/internal/store"
)

// FieldKind is the closed set of custom field shapes exposed by the People UI.
type FieldKind string

const (
	FieldKindText     FieldKind = "text"
	FieldKindLongText FieldKind = "long_text"
	FieldKindNumber   FieldKind = "number"
	FieldKindCheckbox FieldKind = "checkbox"
	FieldKindDate     FieldKind = "date"
	FieldKindDateTime FieldKind = "datetime"
	FieldKindURL      FieldKind = "url"
	FieldKindEmail    FieldKind = "email"
	FieldKindPhone    FieldKind = "phone"
	FieldKindJSON     FieldKind = "json"
)

// EditableFieldKinds is the stable order used by field type selectors.
var EditableFieldKinds = []FieldKind{
	FieldKindText,
	FieldKindLongText,
	FieldKindNumber,
	FieldKindCheckbox,
	FieldKindDate,
	FieldKindDateTime,
	FieldKindURL,
	FieldKindEmail,
	FieldKindPhone,
	FieldKindJSON,
}

// DefinitionInput maps a UI field choice onto the persisted storage and
// presentation types. Slugs are deliberately absent and generated by the
// server from Label.
func (f NewField) DefinitionInput() (DefinitionInput, error) {
	input := DefinitionInput{Label: f.Label, Cardinality: f.Cardinality}
	switch f.Kind {
	case FieldKindText:
		input.ValueType, input.FieldType = store.AttributeValueText, store.AttributeFieldText
	case FieldKindLongText:
		input.ValueType, input.FieldType = store.AttributeValueText, store.AttributeFieldTextarea
	case FieldKindNumber:
		input.ValueType, input.FieldType = store.AttributeValueReal, store.AttributeFieldText
	case FieldKindCheckbox:
		input.ValueType, input.FieldType = store.AttributeValueBoolean, store.AttributeFieldCheckbox
	case FieldKindDate:
		input.ValueType, input.FieldType = store.AttributeValueDate, store.AttributeFieldDate
	case FieldKindDateTime:
		input.ValueType, input.FieldType = store.AttributeValueTimestamp, store.AttributeFieldTimestamp
	case FieldKindURL:
		input.ValueType, input.FieldType = store.AttributeValueText, store.AttributeFieldURL
	case FieldKindEmail:
		input.ValueType, input.FieldType = store.AttributeValueText, store.AttributeFieldEmail
	case FieldKindPhone:
		input.ValueType, input.FieldType = store.AttributeValueText, store.AttributeFieldPhone
	case FieldKindJSON:
		input.ValueType, input.FieldType = store.AttributeValueJSON, store.AttributeFieldJSON
	default:
		return DefinitionInput{}, fmt.Errorf("unsupported people field kind %q", f.Kind)
	}
	return input, nil
}
