package mcp

import (
	"context"
	"testing"

	sdkmcp "github.com/modelcontextprotocol/go-sdk/mcp"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
	"go.opentelemetry.io/otel/trace"
)

// A notification may legally arrive with no params object at all, and Claude
// Code sends notifications/initialized that way. The SDK decodes the absent
// object into a typed-nil *InitializedParams, and GetParams boxes it into the
// non-nil Params interface — so a plain `params != nil` passes and the
// autogenerated GetMeta dereferences the nil receiver. That panic killed the
// whole server on every connect, before tools/list ever got a response (#629).
func TestTraceMiddlewareToleratesParamsAbsentFromTheMessage(t *testing.T) {
	checks := assert.New(t)
	must := require.New(t)

	var reached bool
	handler := traceMiddleware(func(context.Context, string, sdkmcp.Request) (sdkmcp.Result, error) {
		reached = true
		return &sdkmcp.ResultBase{}, nil
	})

	// Params left at its zero value: a nil pointer inside a non-nil interface,
	// which is exactly what the wire message without "params" produces.
	req := &sdkmcp.ServerRequest[*sdkmcp.InitializedParams]{}
	// This is the comparison the production code performs, kept in a variable
	// because it must stay a Go interface comparison. require.NotNil reflects,
	// and reports a typed-nil pointer as nil — the opposite answer, which would
	// quietly turn this into a test of nothing.
	interfaceIsNonNil := req.GetParams() != nil
	must.True(interfaceIsNonNil, "an interface holding a typed nil is not itself nil; without that this reproduces nothing")

	result, err := handler(context.Background(), "notifications/initialized", req)

	must.NoError(err)
	checks.True(reached, "the notification must still reach the next handler")
	checks.NotNil(result)
}

// The guard must not cost the feature it guards: a request that does carry
// trace context still has it extracted, so spans join the client's trace.
func TestTraceMiddlewareExtractsTraceContextFromMeta(t *testing.T) {
	checks := assert.New(t)
	must := require.New(t)

	const (
		wantTraceID = "4bf92f3577b34da6a3ce929d0e0e4736"
		wantSpanID  = "00f067aa0ba902b7"
	)

	var got trace.SpanContext
	handler := traceMiddleware(func(ctx context.Context, _ string, _ sdkmcp.Request) (sdkmcp.Result, error) {
		got = trace.SpanContextFromContext(ctx)
		return &sdkmcp.ResultBase{}, nil
	})

	params := &sdkmcp.CallToolParamsRaw{}
	params.SetMeta(map[string]any{
		"traceparent": "00-" + wantTraceID + "-" + wantSpanID + "-01",
	})
	req := &sdkmcp.ServerRequest[*sdkmcp.CallToolParamsRaw]{Params: params}

	_, err := handler(context.Background(), "tools/call", req)

	must.NoError(err)
	checks.Equal(wantTraceID, got.TraceID().String())
	checks.True(got.IsValid())
}

// A params object present but carrying no _meta is the common case, and must be
// as quiet as an absent one.
func TestTraceMiddlewareToleratesParamsWithoutMeta(t *testing.T) {
	checks := assert.New(t)
	must := require.New(t)

	var reached bool
	handler := traceMiddleware(func(context.Context, string, sdkmcp.Request) (sdkmcp.Result, error) {
		reached = true
		return &sdkmcp.ResultBase{}, nil
	})

	req := &sdkmcp.ServerRequest[*sdkmcp.InitializedParams]{Params: &sdkmcp.InitializedParams{}}

	_, err := handler(context.Background(), "notifications/initialized", req)

	must.NoError(err)
	checks.True(reached)
}
