package store

import (
	"os"
	"strings"
	"testing"
	"time"

	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
)

// Verbatim consent DDL from f5f59b1c, the last schema before provider_consents.
const legacyConsentDDLSQLite = `
CREATE TABLE IF NOT EXISTS person_inference_consents (
    id                   INTEGER PRIMARY KEY AUTOINCREMENT,
    profile_fingerprint  TEXT NOT NULL REFERENCES person_inference_profiles(fingerprint),
    granted_by           TEXT NOT NULL,
    granted_at           DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    revoked_by           TEXT,
    revoked_at           DATETIME,
    CHECK ((revoked_by IS NULL) = (revoked_at IS NULL))
);
CREATE UNIQUE INDEX IF NOT EXISTS idx_person_inference_consents_active
    ON person_inference_consents(profile_fingerprint)
    WHERE revoked_at IS NULL;
CREATE TABLE IF NOT EXISTS person_enrichment_consents (
    id                  INTEGER PRIMARY KEY,
    profile_fingerprint TEXT NOT NULL REFERENCES person_enrichment_profiles(fingerprint),
    granted_by          TEXT NOT NULL,
    granted_at          DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    revoked_by          TEXT,
    revoked_at          DATETIME,
    CHECK ((revoked_by IS NULL) = (revoked_at IS NULL))
);
CREATE UNIQUE INDEX IF NOT EXISTS person_enrichment_consents_active
    ON person_enrichment_consents(profile_fingerprint)
    WHERE revoked_at IS NULL;
CREATE TABLE IF NOT EXISTS person_semantic_embedding_consents (
    id                  INTEGER PRIMARY KEY AUTOINCREMENT,
    profile_fingerprint TEXT NOT NULL REFERENCES person_semantic_embedding_profiles(fingerprint),
    granted_by          TEXT NOT NULL,
    granted_at          DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    revoked_by          TEXT,
    revoked_at          DATETIME,
    CHECK ((revoked_by IS NULL) = (revoked_at IS NULL))
);
CREATE UNIQUE INDEX IF NOT EXISTS idx_person_semantic_embedding_consents_active
    ON person_semantic_embedding_consents(profile_fingerprint)
    WHERE revoked_at IS NULL;`

const legacyConsentDDLPostgreSQL = `
CREATE TABLE IF NOT EXISTS person_inference_consents (
    id                   BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    profile_fingerprint  TEXT NOT NULL REFERENCES person_inference_profiles(fingerprint),
    granted_by           TEXT NOT NULL,
    granted_at           TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    revoked_by           TEXT,
    revoked_at           TIMESTAMPTZ,
    CHECK ((revoked_by IS NULL) = (revoked_at IS NULL))
);
CREATE UNIQUE INDEX IF NOT EXISTS idx_person_inference_consents_active
    ON person_inference_consents(profile_fingerprint)
    WHERE revoked_at IS NULL;
CREATE TABLE IF NOT EXISTS person_enrichment_consents (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    profile_fingerprint TEXT NOT NULL REFERENCES person_enrichment_profiles(fingerprint),
    granted_by          TEXT NOT NULL,
    granted_at          TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    revoked_by          TEXT,
    revoked_at          TIMESTAMPTZ,
    CHECK ((revoked_by IS NULL) = (revoked_at IS NULL))
);
CREATE UNIQUE INDEX IF NOT EXISTS person_enrichment_consents_active
    ON person_enrichment_consents(profile_fingerprint)
    WHERE revoked_at IS NULL;
CREATE TABLE IF NOT EXISTS person_semantic_embedding_consents (
    id                  BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    profile_fingerprint TEXT NOT NULL REFERENCES person_semantic_embedding_profiles(fingerprint),
    granted_by          TEXT NOT NULL,
    granted_at          TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    revoked_by          TEXT,
    revoked_at          TIMESTAMPTZ,
    CHECK ((revoked_by IS NULL) = (revoked_at IS NULL))
);
CREATE UNIQUE INDEX IF NOT EXISTS idx_person_semantic_embedding_consents_active
    ON person_semantic_embedding_consents(profile_fingerprint)
    WHERE revoked_at IS NULL;`

func TestProviderConsentMigrationKeepsHistoryAndIDs(t *testing.T) {
	require := require.New(t)
	assert := assert.New(t)
	ctx := t.Context()
	st, personID := newPersonFactLedgerStore(t)
	if IsPostgresURL(os.Getenv("MSGVAULT_TEST_DB")) {
		require.True(st.IsPostgreSQL(), "MSGVAULT_TEST_DB must not fall back to SQLite")
	}
	fingerprint := strings.Repeat("c", 64)
	insertRawConsentProfiles(t, st, fingerprint)

	ddl, overriding := legacyConsentDDLSQLite, ""
	if st.IsPostgreSQL() {
		ddl, overriding = legacyConsentDDLPostgreSQL, " OVERRIDING SYSTEM VALUE"
	}
	_, err := st.db.ExecContext(ctx, ddl)
	require.NoError(err)

	base := time.Date(2026, 3, 4, 5, 6, 7, 0, time.UTC)
	at := func(hours int) time.Time { return base.Add(time.Duration(hours) * time.Hour) }
	type row struct {
		table     string
		id        int64
		grantedBy string
		grantedAt time.Time
		revokedBy any
		revokedAt any
	}
	rows := []row{
		{"person_inference_consents", 1, "alice", at(0), "alice-revoker", at(1)},
		{"person_inference_consents", 2, "bob", at(2), nil, nil},
		{"person_enrichment_consents", 1, "carol", at(3), "carol-revoker", at(4)},
		{"person_enrichment_consents", 7, "dave", at(5), nil, nil},
		{"person_semantic_embedding_consents", 1, "erin", at(6), "erin-revoker", at(7)},
		{"person_semantic_embedding_consents", 3, "frank", at(8), nil, nil},
	}
	for _, seed := range rows {
		_, err := st.db.ExecContext(ctx, `INSERT INTO `+seed.table+`
			(id, profile_fingerprint, granted_by, granted_at, revoked_by, revoked_at)`+overriding+`
			VALUES (?, ?, ?, ?, ?, ?)`,
			seed.id, fingerprint, seed.grantedBy, seed.grantedAt, seed.revokedBy, seed.revokedAt)
		require.NoError(err, seed.table)
	}
	_, err = st.db.ExecContext(ctx, `INSERT INTO person_enrichment_work
		(person_id, profile_fingerprint, trigger_mask, trigger_generation, due_at)
		VALUES (?, ?, 1, 'consent:7', ?)`, personID, fingerprint, at(9))
	require.NoError(err)

	_, err = st.db.ExecContext(ctx, `DELETE FROM applied_migrations WHERE name = ?`, migrationProviderConsentsV1)
	require.NoError(err)
	require.NoError(st.InitSchema())

	for _, table := range []string{
		"person_inference_consents", "person_enrichment_consents", "person_semantic_embedding_consents",
	} {
		exists, err := st.tableExistsContext(t.Context(), table)
		require.NoError(err)
		assert.False(exists, table+" must be dropped after the copy")
	}

	statuses := map[string]*ProviderConsentStatus{}
	statuses["person_inference_consents"], err = st.GetPersonInferenceConsentStatus(ctx, fingerprint)
	require.NoError(err)
	statuses["person_enrichment_consents"], err = st.PersonEnrichmentConsentStatus(ctx, fingerprint)
	require.NoError(err)
	statuses["person_semantic_embedding_consents"], err = st.GetPersonSemanticEmbeddingConsentStatus(ctx, fingerprint)
	require.NoError(err)
	for _, seed := range rows {
		status := statuses[seed.table]
		require.True(status.Active, seed.table)
		got := status.Consent
		if seed.revokedBy != nil {
			got = status.LastRevoked
		}
		require.NotNil(got, seed.table)
		assert.Equal(seed.id, got.ID, seed.table)
		assert.Equal(fingerprint, got.ProfileFingerprint, seed.table)
		assert.Equal(seed.grantedBy, got.GrantedBy, seed.table)
		assert.True(seed.grantedAt.Equal(got.GrantedAt), "%s granted_at %v", seed.table, got.GrantedAt)
		if seed.revokedBy == nil {
			assert.Nil(got.RevokedBy, seed.table)
			assert.Nil(got.RevokedAt, seed.table)
			continue
		}
		require.NotNil(got.RevokedBy, seed.table)
		require.NotNil(got.RevokedAt, seed.table)
		assert.Equal(seed.revokedBy, *got.RevokedBy, seed.table)
		revokedAt, ok := seed.revokedAt.(time.Time)
		require.True(ok, seed.table)
		assert.True(revokedAt.Equal(*got.RevokedAt), "%s revoked_at %v", seed.table, *got.RevokedAt)
	}

	var generation string
	require.NoError(st.db.QueryRowContext(ctx, `SELECT trigger_generation FROM person_enrichment_work
		WHERE person_id = ? AND profile_fingerprint = ?`, personID, fingerprint).Scan(&generation))
	assert.Equal("consent:7", generation)

	changed, err := st.RevokePersonInferenceConsent(ctx, fingerprint, "cli")
	require.NoError(err)
	require.True(changed)
	next, _, err := st.GrantPersonInferenceConsent(ctx, fingerprint, "cli")
	require.NoError(err)
	assert.Equal(int64(3), next.ID, "IDs keep growing within a purpose after migration")
}
