package skills

import (
	"strings"
	"testing"

	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
)

// parseFrontmatter extracts name and description from the YAML
// frontmatter block we generate (simple key: value lines between
// --- fences). We parse by hand to avoid a YAML dependency.
func parseFrontmatter(t *testing.T, content string) (name, description string) {
	t.Helper()
	require.True(t, strings.HasPrefix(content, "---\n"),
		"content must start with frontmatter fence")
	rest := content[len("---\n"):]
	end := strings.Index(rest, "\n---\n")
	require.GreaterOrEqual(t, end, 0, "frontmatter must be closed with ---")
	for line := range strings.SplitSeq(rest[:end], "\n") {
		key, value, found := strings.Cut(line, ":")
		if !found {
			continue
		}
		switch strings.TrimSpace(key) {
		case "name":
			name = strings.TrimSpace(value)
		case "description":
			description = strings.TrimSpace(value)
		}
	}
	return name, description
}

func TestRender_AllSkills(t *testing.T) {
	rendered, err := Render("1.2.3")
	require.NoError(t, err)

	wantNames := []string{
		"msgvault-analytics", "msgvault-attachments", "msgvault-search",
	}
	var gotNames []string
	for _, sk := range rendered {
		gotNames = append(gotNames, sk.Name)
	}
	assert.Equal(t, wantNames, gotNames, "skills sorted by name")

	for _, sk := range rendered {
		name, description := parseFrontmatter(t, sk.Content)
		assert.Equal(t, sk.Name, name,
			"frontmatter name must match directory name")
		assert.NotEmpty(t, description)
		assert.LessOrEqual(t, len(description), 1024)
		assert.Contains(t, sk.Content, Marker,
			"rendered skill must carry the generated-by marker")
		assert.Contains(t, sk.Content, "v1.2.3",
			"marker line embeds the version")
		assert.NotContains(t, sk.Content, "{{",
			"no unrendered template actions")
		// every skill embeds the shared basics section
		assert.Contains(t, sk.Content, "## msgvault conventions")
	}
}

func TestRender_VersionDefaultsSafely(t *testing.T) {
	rendered, err := Render("dev")
	require.NoError(t, err)
	require.NotEmpty(t, rendered)
	assert.Contains(t, rendered[0].Content, "generated by msgvault vdev")
}
