// Package skills renders and installs agent skill files (SKILL.md, per
// the open agent-skills standard used by Claude Code and Codex) that
// teach coding agents the msgvault read-only CLI workflows.
package skills

import (
	"embed"
	"fmt"
	"sort"
	"strings"
	"text/template"
)

//go:embed templates/*.tmpl
var templatesFS embed.FS

// Marker identifies SKILL.md files written by the installer. Install
// only overwrites, and uninstall only removes, files containing this
// stable phrase (the version suffix in the rendered line varies).
const Marker = "generated by msgvault"

// Skill is one rendered agent skill.
type Skill struct {
	Name    string // skill directory name, e.g. "msgvault-search"
	Content string // full SKILL.md content
}

// Render renders every embedded skill template (files not prefixed
// with "_") with the given version, returning skills sorted by name.
func Render(version string) ([]Skill, error) {
	tmpl, err := template.ParseFS(templatesFS, "templates/*.tmpl")
	if err != nil {
		return nil, fmt.Errorf("parse skill templates: %w", err)
	}
	entries, err := templatesFS.ReadDir("templates")
	if err != nil {
		return nil, fmt.Errorf("read embedded templates: %w", err)
	}
	data := struct{ Version string }{Version: version}
	var out []Skill
	for _, entry := range entries {
		base := entry.Name()
		if strings.HasPrefix(base, "_") {
			continue // shared partial, not a skill
		}
		var buf strings.Builder
		if err := tmpl.ExecuteTemplate(&buf, base, data); err != nil {
			return nil, fmt.Errorf("render skill template %s: %w", base, err)
		}
		out = append(out, Skill{
			Name:    strings.TrimSuffix(base, ".md.tmpl"),
			Content: buf.String(),
		})
	}
	sort.Slice(out, func(i, j int) bool { return out[i].Name < out[j].Name })
	return out, nil
}
